/**
 * Auto-generated TypeScript definitions
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * 
 * Generated at: 2025-11-21 10:30:01
 * Run `php artisan generate:ts-types` to regenerate
 */

export type ActivityStatus = 'active' | 'inactive' | 'suspended' | 'deleted';

export type AuthenticationProvider = 'email' | 'google' | 'github' | 'microsoft';

export type Language = 'en' | 'fr' | 'es' | 'de' | 'it' | 'pt' | 'ru' | 'tr' | 'ja' | 'zh' | 'ar' | 'hi' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'sd' | 'sy' | 'ur' | 'uk' | 'vi' | 'ms' | 'nl' | 'no' | 'pl' | 'ro' | 'sk' | 'sl' | 'sv';

export type QueuePriority = 'low' | 'medium' | 'high';

export type RBACPermission = 'can_access_control_panel' | 'can_impersonate_users' | 'can_access_backups' | 'can_access_health_check' | 'can_access_activity_logs' | 'can_manage_settings';

export type RBACRole = 'super_admin' | 'admin' | 'user';

