/**
 * Auto-generated TypeScript definitions
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * Generated at: 2026-01-13 10:09:38
 * Run `php artisan generate:ts-types` to regenerate
 */

export type ActivityStatus = 'active' | 'inactive' | 'suspended' | 'deleted';

export type AuthenticationProvider = 'email' | 'google' | 'github' | 'microsoft';

export type Language =
    | 'en'
    | 'fr'
    | 'es'
    | 'de'
    | 'it'
    | 'pt'
    | 'ru'
    | 'tr'
    | 'ja'
    | 'zh'
    | 'ar'
    | 'hi'
    | 'bn'
    | 'ta'
    | 'te'
    | 'mr'
    | 'gu'
    | 'kn'
    | 'ml'
    | 'pa'
    | 'sd'
    | 'sy'
    | 'ur'
    | 'uk'
    | 'vi'
    | 'ms'
    | 'nl'
    | 'no'
    | 'pl'
    | 'ro'
    | 'sk'
    | 'sl'
    | 'sv';

export type ModulesMailgunEmailEventType =
    | 'accepted'
    | 'delivered'
    | 'failed'
    | 'rejected'
    | 'opened'
    | 'clicked'
    | 'unsubscribed'
    | 'complained'
    | 'stored';

export type ModulesMailgunEmailStatus = 'attempted' | 'accepted' | 'delivered' | 'dropped' | 'bounced' | 'failed' | 'complained';

export type ModulesTasksTaskPriority = 'low' | 'normal' | 'high' | 'critical';

export type ModulesTasksTaskType = 'task' | 'bug' | 'feature' | 'documentation' | 'other';

export type ModulesTasksTaskViewType = 'list' | 'kanban' | 'calendar' | 'gantt';

export type NotificationDeliveryMethod = 'none' | 'email' | 'push' | 'email_push';

export type QueuePriority = 'low' | 'medium' | 'high';

export type RBACPermission =
    | 'access:control-panel'
    | 'access:impersonate-users'
    | 'access:backups'
    | 'access:health-check'
    | 'access:activity-logs'
    | 'manage:settings'
    | 'access:api'
    | 'create:users'
    | 'read:users'
    | 'update:users'
    | 'delete:users'
    | 'restore:users'
    | 'create:roles'
    | 'read:roles'
    | 'update:roles'
    | 'delete:roles'
    | 'restore:roles'
    | 'create:api-tokens'
    | 'read:api-tokens'
    | 'update:api-tokens'
    | 'delete:api-tokens'
    | 'create:clients'
    | 'read:clients'
    | 'update:clients'
    | 'delete:clients'
    | 'restore:clients';

export type RBACRole = 'super_admin' | 'admin' | 'user';
