/**
 * Auto-generated TypeScript definitions
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * 
 * Generated at: 2026-01-13 10:09:38
 * Run `php artisan generate:ts-types` to regenerate
 */

import type {
  ActivityStatus,
  BillingStatus,
  ModulesMailgunEmailEventType,
  ModulesMailgunEmailStatus,
  ModulesTasksTaskPriority,
  ModulesTasksTaskType,
  ModulesTasksTaskViewType
} from './enums';

export interface Activity {
  id: number;
  log_name: string;
  description: string;
  event?: string;
  subject_type?: string;
  subject_id?: string;
  causer_type?: string;
  causer_id?: string;
  properties: mixed[];
  created_at: string;
  updated_at: string;

  // Relationships
  causer?: User|null;
  subject?: Model|null;
}

export interface Client {
  id: string;
  name: string;
  contact_name: string;
  contact_email: string;
  contact_phone?: string;
  address?: string;
  postal_code?: string;
  city?: string;
  country?: string;
  status: ActivityStatus;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  users?: User[];
  billingInfo?: ClientBillingInfo|null;
  subscriptions?: Subscription[];
  invoices?: Invoice[];
  activities?: Activity[];
  tasks?: Task[];
}

export interface ClientBillingInfo {
  id: string;
  client_id: string;
  company: string;
  tax_number: string;
  vat_number: string;
  address: string;
  postal_code: string;
  city: string;
  country: string;
  billing_email: string;
  billing_phone: string;
  notes?: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  client?: Client;
}

export interface ClientUser {
  client_id: string;
  user_id: string;
  created_at?: string;
  updated_at?: string;
}

export interface EmailEvent {
  id: string;
  email_message_id: string;
  event_type: EmailEventType;
  mailgun_event_id?: string;
  severity?: string;
  reason?: string;
  recipient?: string;
  ip_address?: string;
  user_agent?: string;
  url?: string;
  raw_payload?: any[];
  occurred_at?: string;
  created_at: string;
  updated_at: string;

  // Relationships
  emailMessage?: EmailMessage;
}

export interface EmailMessage {
  id: string;
  tenant_id?: string;
  mailable_class?: string;
  subject: string;
  from_address: string;
  from_name?: string;
  to_address: string;
  to_name?: string;
  cc?: any[];
  bcc?: any[];
  tags?: any[];
  mailgun_message_id?: string;
  correlation_id?: string;
  status: EmailStatus;
  sent_at?: string;
  created_at: string;
  updated_at: string;

  // Relationships
  events?: EmailEvent[];
}

export interface Invoice {
  id: string;
  invoice_id: string;
  client_id: string;
  subscription_id?: string;
  total: number;
  currency?: string;
  status: BillingStatus;
  paid_at?: string;
  due_date?: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  client?: Client;
  subscription?: Subscription|null;
  payments?: Payment[];
}

export interface Payment {
  id: string;
  invoice_id: string;
  provider: string;
  provider_payment_id?: string;
  amount: number;
  currency?: string;
  status: BillingStatus;
  paid_at?: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  invoice?: Invoice;
}

export interface Plan {
  id: string;
  name: string;
  price: number;
  interval: string;
  trial_days?: number;
  features?: any[];
  status: ActivityStatus;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  subscriptions?: Subscription[];
}

export interface Subscription {
  id: string;
  client_id: string;
  plan_id: string;
  status: ActivityStatus;
  starts_at?: string;
  ends_at?: string;
  trial_ends_at?: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  client?: Client;
  plan?: Plan;
  invoices?: Invoice[];
}

export interface Task {
  id: string;
  taskable_id: string;
  taskable_type: string;
  title: string;
  description?: string;
  type: TaskType;
  priority: TaskPriority;
  status_id: string;
  order?: number;
  due_date?: string;
  completed_at?: string;
  created_by_id?: string;
  assigned_to_id?: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  taskable?: Model;
  status?: TaskStatus;
  createdBy?: User|null;
  assignedTo?: User|null;
}

export interface TaskStatus {
  id: string;
  name: string;
  color: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  tasks?: Task[];
}

export interface TaskView {
  id: string;
  taskable_type: string;
  taskable_id: string;
  is_default: boolean;
  name: string;
  slug: string;
  type: TaskViewType;
  metadata?: any[];

  // Relationships
  taskable?: Model;
  statuses?: TaskStatus[];
}

export interface Permission {
  id: number;
  name: string;
  guard_name: string;
  created_at: string;
  updated_at: string;

  // Relationships
  roles?: Role[];
  activities?: Activity[];
}

export interface Role {
  id: number;
  name: string;
  guard_name: string;
  icon?: string;
  color?: string;
  created_at: string;
  updated_at: string;

  // Relationships
  permissions?: Permission[];
  users?: User[];
  activities?: Activity[];
}

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;
  avatar?: string | null;
  status: ActivityStatus;
  provider: string;
  email_verified_at?: string;
  two_factor_confirmed_at?: string;
  preferences?: any[];
  created_at: string;
  updated_at: string;
  deleted_at?: string;

  // Relationships
  roles?: Role[];
  permissions?: Permission[];
  activities?: Activity[];
  clients?: Client[];
}

