/**
 * Auto-generated TypeScript definitions
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * 
 * Generated at: 2025-11-21 10:30:01
 * Run `php artisan generate:ts-types` to regenerate
 */

import type {
  ActivityStatus,
  AuthenticationProvider
} from './enums';

export interface Client {
  id: string;
  name: string;
  contact_name: string;
  contact_email: string;
  contact_phone?: string;
  address?: string;
  postal_code?: string;
  city?: string;
  country?: string;
  status?: ActivityStatus;
  deleted_at?: string;
  created_at?: string;
  updated_at?: string;

  // Relationships
  users?: User[];
  billingInfo?: ClientBillingInfo;
  subscriptions?: Subscription[];
  invoices?: Invoice[];
}

export interface ClientBillingInfo {
  id: string;
  client_id: string;
  company: string;
  tax_number: string;
  vat_number: string;
  address: string;
  postal_code: string;
  city: string;
  country: string;
  billing_email: string;
  billing_phone: string;
  notes?: string;
  deleted_at?: string;
  created_at?: string;
  updated_at?: string;

  // Relationships
  client?: Client;
}

export interface ClientUser {
  client_id: string;
  user_id: string;
  created_at?: string;
  updated_at?: string;
}

export interface Invoice {
  id: string;
  invoice_id: string;
  client_id: string;
  subscription_id?: string;
  total: number;
  currency?: string;
  status: string;
  paid_at?: string;
  due_date?: string;
  deleted_at?: string;
  created_at?: string;
  updated_at?: string;

  // Relationships
  client?: Client;
  subscription?: Subscription;
  payments?: Payment[];
}

export interface Payment {
  id: string;
  invoice_id: string;
  provider: string;
  provider_payment_id?: string;
  amount: number;
  currency?: string;
  status: string;
  paid_at?: string;
  deleted_at?: string;
  created_at?: string;
  updated_at?: string;

  // Relationships
  invoice?: Invoice;
}

export interface Plan {
  id: string;
  name: string;
  price: number;
  interval: string;
  trial_days?: number;
  features?: any[];
  status?: ActivityStatus;
  deleted_at?: string;
  created_at?: string;
  updated_at?: string;

  // Relationships
  subscriptions?: Subscription[];
}

export interface Subscription {
  id: string;
  client_id: string;
  plan_id: string;
  status?: ActivityStatus;
  starts_at?: string;
  ends_at?: string;
  trial_ends_at?: string;
  deleted_at?: string;
  created_at?: string;
  updated_at?: string;

  // Relationships
  client?: Client;
  plan?: Plan;
  invoices?: Invoice[];
}

export interface SocialiteProvider {
  id: string;
  name: string;
  client_id?: string;
  client_secret?: string;
  redirect_uri?: string;
  is_enabled?: boolean;
  sort_order?: number;
  created_at?: string;
  updated_at?: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;
  status?: ActivityStatus;
  email_verified_at?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
  two_factor_confirmed_at?: string;
  provider: string;

  // Relationships
  roles?: Role[];
  permissions?: Permission[];
}

export interface Notification {
  id: string;
  title: string;
  body: string;
  action_url?: string;
  read_at?: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string;
}